name: dateplan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  flutter_gen:
  get: 4.6.5
  dio: 4.0.6
  dropdown_search:
  rflutter_alert:
  encrypt:
  flutter_file_saver:
  rxdart:
  url_launcher:
  animated_text_kit:
  google_fonts:
  shared_preferences: ^2.0.15
  google_maps_flutter:
  font_awesome_flutter: ^10.3.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_advanced_drawer:
#  flutter_polyline_points:
  flutter_polyline_points_plus:
  location:
  flutter_background_service:
  dropdown_plus:
  intl:
  vibration:
  sms_autofill:
  timer_count_down:
  lottie:
  carousel_slider:
  image_cropper:
  image_picker:
  flutter_gif:
  iconsax:
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:
  geocoding:
  amplify_flutter: 1.3.3
  amplify_api:
  amplify_auth_cognito:

#  simple_animations:


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
  location_platform_interface: 3.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/icon/
